// Report Service — Generate WhatsApp-friendly text reports and CSV exports

import StateManager from '../core/state.js';
import VisitorService from './VisitorService.js';
import EngagementService from './EngagementService.js';
import ReminderService from './ReminderService.js';
import { INTERACTION_TYPE_LABELS, ORGANIZATION, APP_VERSION } from '../utils/constants.js';

function monthName(date) {
    return date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
}

function startOfMonth(date) {
    const d = new Date(date);
    d.setDate(1);
    d.setHours(0, 0, 0, 0);
    return d;
}

function endOfMonth(date) {
    const d = new Date(date);
    d.setMonth(d.getMonth() + 1);
    d.setDate(0);
    d.setHours(23, 59, 59, 999);
    return d;
}

function groupBy(arr, keyFn) {
    const map = new Map();
    arr.forEach(item => {
        const k = keyFn(item);
        map.set(k, (map.get(k) || 0) + 1);
    });
    return map;
}

class ReportService {
    /**
     * Generate a plain-text monthly report suitable for pasting into WhatsApp.
     * @param {Date} [forDate] - any date within the target month (defaults to today)
     * @returns {string}
     */
    generateMonthlyTextReport(forDate = new Date()) {
        const settings = StateManager.getSettings();
        const orgName = settings.organizationName || ORGANIZATION;

        const monthStart = startOfMonth(forDate);
        const monthEnd = endOfMonth(forDate);

        const visitors = VisitorService.getAll();
        const allVisitorsRaw = StateManager.getVisitors();
        const interactions = StateManager.getInteractions();
        const reminderActions = StateManager.getReminderActions();

        // New visitors created this month
        const newThisMonth = visitors.filter(v => {
            const created = new Date(v.createdAt);
            return created >= monthStart && created <= monthEnd;
        });

        // Interactions this month
        const monthInteractions = interactions.filter(i => {
            const date = new Date(i.interactionDate);
            return date >= monthStart && date <= monthEnd;
        });

        // Interactions by type
        const byType = groupBy(monthInteractions, i => i.interactionType || 'other');

        // Reminder actions completed this month
        const completedActions = reminderActions.filter(a => {
            const date = new Date(a.actionAt);
            return date >= monthStart && date <= monthEnd && a.action === 'contacted';
        });

        // Top cities
        const cityCounts = new Map();
        visitors.forEach(v => {
            const city = v.city?.trim();
            if (city) cityCounts.set(city, (cityCounts.get(city) || 0) + 1);
        });
        const topCities = [...cityCounts.entries()]
            .sort((a, b) => b[1] - a[1])
            .slice(0, 5);

        // Needs attention (lapsed)
        const { lapsed, neverContacted } = EngagementService.getLapsedVisitors();

        // Build report
        const lines = [];
        lines.push(`*Monthly Report — ${monthName(forDate)}*`);
        lines.push(orgName);
        lines.push('─────────────────────');
        lines.push(`Active visitors: ${visitors.length}`);
        lines.push(`New this month: ${newThisMonth.length}`);

        if (monthInteractions.length > 0) {
            const typeBreakdown = [...byType.entries()]
                .sort((a, b) => b[1] - a[1])
                .map(([type, count]) => `${count} ${this._prettyType(type)}`)
                .join(', ');
            lines.push(`Interactions: ${monthInteractions.length} (${typeBreakdown})`);
        } else {
            lines.push(`Interactions: 0`);
        }

        lines.push(`Reminders actioned: ${completedActions.length}`);
        lines.push(`Needs attention: ${lapsed.length} lapsed, ${neverContacted.length} never contacted`);

        if (topCities.length > 0) {
            const cityLine = topCities.map(([c, n]) => `${c} (${n})`).join(', ');
            lines.push(`Top cities: ${cityLine}`);
        }

        lines.push('─────────────────────');
        lines.push(`Generated by Dnyani Mitra v${APP_VERSION}`);

        return lines.join('\n');
    }

    _prettyType(type) {
        const label = INTERACTION_TYPE_LABELS[type];
        if (!label) return type;
        // Strip emoji prefix for clean text report
        return label.replace(/^[^\w]+\s*/, '').toLowerCase();
    }

    /**
     * Generate a CSV string of all visitors with summary columns.
     * Fields: Name, Phone, Email, City, Category, DoB, TotalInteractions, LastInteractionDate, EngagementScore, ConsentGiven
     */
    generateVisitorCSV() {
        const visitors = VisitorService.getAll();
        const interactions = StateManager.getInteractions();

        // Count interactions per visitor
        const interactionCounts = new Map();
        const lastInteractionDates = new Map();
        interactions.forEach(i => {
            interactionCounts.set(i.visitorId, (interactionCounts.get(i.visitorId) || 0) + 1);
            const existing = lastInteractionDates.get(i.visitorId);
            if (!existing || new Date(i.interactionDate) > new Date(existing)) {
                lastInteractionDates.set(i.visitorId, i.interactionDate);
            }
        });

        const headers = [
            'Name', 'Phone', 'Email', 'City', 'Category', 'Tags',
            'DateOfBirth', 'MarriageDate',
            'TotalInteractions', 'LastInteractionDate', 'EngagementScore',
            'ConsentGiven', 'DoNotContact', 'ContactFrequencyDays',
            'CreatedAt', 'UpdatedAt'
        ];

        const rows = visitors.map(v => {
            const self = v.contacts?.find(c => c.relationType === 'SELF');
            return [
                self?.name || '',
                self?.phones?.[0] || '',
                self?.emails?.[0] || '',
                v.city || '',
                v.category || '',
                (v.tags || []).join('; '),
                self?.dob || '',
                self?.marriageDate || '',
                interactionCounts.get(v.id) || 0,
                lastInteractionDates.get(v.id) || '',
                v.engagementScore ?? 0,
                v.consentGiven ? 'yes' : 'no',
                v.doNotContact ? 'yes' : 'no',
                v.contactFrequencyDays ?? '',
                v.createdAt || '',
                v.updatedAt || ''
            ];
        });

        return this._rowsToCSV([headers, ...rows]);
    }

    _rowsToCSV(rows) {
        return rows.map(row =>
            row.map(cell => {
                const s = String(cell ?? '');
                // Quote if contains comma, quote, or newline
                if (/[",\n]/.test(s)) {
                    return `"${s.replace(/"/g, '""')}"`;
                }
                return s;
            }).join(',')
        ).join('\n');
    }
}

export default new ReportService();
